config/routes.rb
Rails.application.routes.draw do

  root to: 'my_shops#index'

  resources :orders

  post 'orders/cost_calculation', to: 'orders#cost_calculation'
  post 'orders/return_city', to: 'orders#return_city'

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  get 'contacts', to: 'my_shops#contacts'
  get 'payment_delivery', to: 'my_shops#payment_delivery'
  get 'order_goods', to: 'my_shops#order_goods'


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange_rate.rb
class ExchangeRate < ApplicationRecord
  validates :usd, :eur,  presence: true
end

app/models/my_shop.rb
class MyShop < ApplicationRecord
  VALID_NAMES = %w(main contacts order_goods payment_delivery)
  validates_inclusion_of :page_name, :in => VALID_NAMES
  validates :page_name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  attr_accessor :exchange_rates
end

app/controllers/my_shops_controller.rb
class MyShopsController < InheritedResources::Base

  def index
    $exchange_rates = get_exchange_rates
    @data =  MyShop.find_by_page_name('main')
  end
  def contacts
    @data =  MyShop.find_by_page_name('contacts')
  end

  def payment_delivery
   @data =  MyShop.find_by_page_name('payment_delivery')
  end

  def order_goods
   @data =  MyShop.find_by_page_name('order_goods')
  end

  private

  def get_exchange_rates
    ex = ExchangeRate.find_by_id(1)
    if ex
      return convert_to_string_and_return_hash ex
    else
      ChangeExchangeRate.new.update_exchange_rates
      return convert_to_string_and_return_hash ExchangeRate.find_by_id(1)
    end
  end

  def convert_to_string_and_return_hash(ex)
    { usd: ex.usd.to_s, eur: ex.eur.to_s }
  end


end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base

  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.valid?
        @order.save

        OrderMailer.with(order: @order).success_order_email.deliver_now

        format.html { redirect_to(@order, notice: 'User was successfully created.') }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def cost_calculation
    cost = CalculationCost.new(params[:value]).show_cost
    render plain: cost
  end

  def return_city
    @stock =  Novaposhta2[params[:value]].warehouses.map(&:description)
  end

  private

  def order_params
    params.require(:order).permit(:count, :name, :last_name, :email, :phone, :city, :stock)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_shops_controller_helper.rb
module MyShopsControllerHelper
end

app/helpers/my_shops_helper.rb
module MyShopsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('/assets/ebay.ico') %>
  </head>

  <body>

  <%= render partial: 'my_shops/naw_bar'%>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <div class="row justify-content-center">
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/my_shops/_naw_bar.html.erb
<header>
<nav class="navbar navbar-expand-md">
  <a href="/" class="navbar-brand">
    <img src="/assets/ebay_logo.png" class="shop_logo" alt="logoShop">
  </a>

  <button class="navbar-toggler em_btn" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <i class="fa fa-bars"></i>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(contacts_path) %>">
        <%= link_to 'Contacts', contacts_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(new_order_path) %>">
        <%= link_to 'Order goods', new_order_path, class: 'nav-link' %>
        </li>
      <li class="nav-item <%= 'active' if current_page?(payment_delivery_path) %>">
        <%= link_to 'Payment / Delivery', payment_delivery_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>
  <div class="shop_ex">
    <% if $exchange_rates %>
      Exchange Rates  USD <%= $exchange_rates[:usd] %>
                      EUR <%= $exchange_rates[:eur] %>
    <% end %>
  </div>
</header>

app/views/my_shops/_show_page.html.erb
<% if @data %>
  <h3 id="page"><%= @data.page.html_safe %></h3>
<% end %>

app/views/my_shops/contacts.html.erb
<%= render partial: 'show_page' %>

app/views/my_shops/index.html.erb
<section id="shop_home">
  <div class="container">
    <div class="row justify-content-center">
      <%= render partial: 'show_page' %>
    </div>
    <%= button_to 'To order', new_order_path, method: :get, class: 'btn btn-success'%>
  </div>
</section>

app/views/my_shops/order_goods.html.erb
<%= render partial: 'show_page' %>

app/views/my_shops/payment_delivery.html.erb
<%= render partial: 'show_page' %>

app/views/orders/_form.html.erb
<%= form_with(model: order, remote:true) do |form| %>

<div class="container justify-content-center">
  <div class="field row">
    <%= form.label :count, class: 'col-2' %>
    <%= form.number_field :count, type: 'number', class: 'col', value: 1, id: 'count-order'  %>
  </div>

  <div class="field row">
    <%= form.label :name, class: 'col-2' %>
    <%= form.text_field :name, class: 'col' %>
  </div>

  <div class="field row">
    <%= form.label :last_name, class: 'col-2' %>
    <%= form.text_field :last_name, class: 'col' %>
  </div>

  <div class="field row">
    <%= form.label :email, class: 'col-2' %>
    <%= form.text_field :email, type: 'email', class: 'col' %>
  </div>

  <div class="field row">
    <%= form.label :phone, class: 'col-2' %>
    <%= form.text_field :phone, type: 'tel', class: 'col' %>
  </div>

  <div class="field row">
    <%= form.label :city, class: 'col-2' %>
    <%= form.select :city, Novaposhta2::City.all.map(&:description), :prompt => 'Select City', class: 'col'%>
  </div>

  <div class="field row">
    <%= form.label :stock, class: 'col-2' %>
    <select  name="order[stock]" id="order-stock"> </select>
  </div>

  <h2 id="show-cost" class="field row">Cost of goods 220$ (<%= 220 * $exchange_rates[:usd].to_d %>) </h2>

  <% if order.errors.any? %>
    <div id="error_explanation row" style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

  <div class="action">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Count</th>
      <th>Name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>City</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.count %></td>
        <td><%= order.name %></td>
        <td><%= order.last_name %></td>
        <td><%= order.email %></td>
        <td><%= order.phone %></td>
        <td><%= order.city %></td>
        <td><%= order.stock %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/return_city.js.erb
$(document).ready(function() {
    $('#order-stock').html(" <%= j options_for_select(@stock, [prompt: 'Select City', class: 'option_class'])%>");
});

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Count:</strong>
  <%= @order.count %>
</p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @order.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @order.phone %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @order.stock %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>